format:
  pdf:
    papersize: a4
    geometry: margin=2.5cm
    mainfont: "Linux Libertine O"
    sansfont: "Linux Biolinum O"
    monofont: "DejaVu Sans Mono"
    toc: true
    toc-depth: 3
    colorlinks: true
    date-format: "MMMM YYYY"
    linkcolor: NavyBlue
    include-in-header:
      text: |
        \usepackage{geometry}
        \usepackage{longtable}
        \usepackage{booktabs}
        \usepackage{array}
        \usepackage{tabularx}
        \usepackage{calc}
        \usepackage{pdflscape}
        \setlength{\tabcolsep}{4pt}
        \renewcommand{\arraystretch}{1.3}
        \AtBeginEnvironment{longtable}{\small}
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhead[L]{\small Erdpuls MÃ¼llrose OER Metadata Package v1.2}
        \fancyhead[R]{\small \thepage}
        \fancyfoot{}
        \publishers{Center for Sustainability Literacy, Citizen Science and Reciprocal Economics}


filters:
  - column-widths.lua
